CREATE TABLE employees (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	full_name VARCHAR(50) NOT NULL,
	salary NUMERIC(12, 2),
	updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE order_status_history (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	order_id BIGINT NOT NULL,
	old_status VARCHAR(50),
	new_status VARCHAR(50),
	changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
