CREATE TABLE roles
(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL UNIQUE

);

CREATE TABLE users
(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	login VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL,	
	role_id INT NOT NULL REFERENCES roles(id)
);

CREATE TABLE states
(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,   
	name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE categories
(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE items
(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
	description TEXT NOT NULL,
	author_id INT NOT NULL REFERENCES users(id),
	state_id INT NOT NULL REFERENCES states(id),
	category_id INT NOT NULL REFERENCES categories(id)
);

CREATE TABLE comments
(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	text VARCHAR (100) NOT NULL,
	item_id INT NOT NULL REFERENCES items(id),
	author_id INT NOT NULL REFERENCES users(id)
);