CREATE TABLE users (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	full_name VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL UNIQUE,
	phone VARCHAR(50) NOT NULL,
	birth_date DATE NOT NULL,
	created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE subscriptions (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT REFERENCES users(id),
	plan_name VARCHAR(50),
	expires_at TIMESTAMP,
	is_active BOOLEAN
);

CREATE TABLE movies (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
	genre VARCHAR(50) NOT NULL,
	release_year INTEGER,
	duration_minutes INTEGER,
	price NUMERIC
);

CREATE TABLE views (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT REFERENCES users(id),
	movie_id BIGINT REFERENCES movies(id),
	watched_at TIMESTAMP DEFAULT NOW(),
	watch_time_minutes INTEGER
);

CREATE TABLE payments (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT REFERENCES users(id),
	amount NUMERIC,
	paid_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE reviews (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT REFERENCES users(id),
	movie_id BIGINT REFERENCES movies(id),
	rating INTEGER,
	created_at TIMESTAMP DEFAULT NOW()
);