DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT NOW()
	
);

CREATE TABLE products (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	price NUMERIC(12, 2) CHECK (price > 0),
	is_active BOOLEAN DEFAULT true,
	created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE orders (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT REFERENCES users(id),
	status VARCHAR(50) NOT NULL,
	created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE order_items (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	order_id INT REFERENCES orders(id),
	product_id INT REFERENCES products,
	quantity INT NOT NULL CHECK (quantity > 0),
	unit_price NUMERIC(12,2) CHECK(unit_price > 0)
);